version: "3.8"

services:
  api:
    build:
      context: ./api               
      dockerfile: Dockerfile
    ports:
      - "8080:8080"              
    depends_on:
      - db

  detect-api:
    build: ./detect-api           
    ports:
      - "5002:5002"

  sentiment-api:
    build: ./sentiment-api        
    ports:
      - "5001:5001"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  db_data:
